apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-12-10T11:53:04.0955479+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: ac494ba0bdd920f354a3c74bb48e60f4d4f8f40fe86791691de75f41148d6f5d
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.4.tgz
    version: 0.1.4
  waardepapieren-frontend:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-12-10T11:53:04.0608473+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/master/api/helm/
      version: 0.1.4
    description: Skeleton application for NL Design running on Gatsby
    digest: a7f93905af425723340f1d083a8d294c29b96bbb5b143022d71bd6f5175be2ca
    name: waardepapieren-frontend
    type: application
    urls:
    - waardepapieren-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2021-12-10T11:53:04.0373964+01:00"
