# Default values for api-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
pwa:
  image:
    image: "ghcr.io/conductionnl/waardepapieren-frontend"
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "dev"
  apiUrl: "https://acc-waardepapieren.hoorn.nl/api"
  meUrl: "https://acc-waardepapieren.hoorn.nl/api/users/me"
  baseUrl: "https://acc-waardepapieren.hoorn.nl/"
  frontendUrl: "https://acc-waardepapieren.hoorn.nl/"
  organization: "placeholder"
  redirectUrl: "null"
  defaultTheme: "hoorn"
    
gateway: 
  enabled: true
  fixtures:
    gateways.yaml:
      App\Entity\Gateway:
        waardepapieren_service_api:
          name: service
          auth: apikey
          apikey: a78828b4-f577-4425-a17c-c217980409e9
          location: https://acc-waardepapieren.hoorn.nl/api/v1/waar
          documentation: https://raw.githubusercontent.com/ConductionNL/waardepapieren-service/master/api/public/schema/openapi.yaml
        waardepapieren_register_api:
          name: register
          auth: apikey
          apikey: a78828b4-f577-4425-a17c-c217980409e9
          location: https://acc-waardepapieren.hoorn.nl/api/v1/wari
          documentation: https://raw.githubusercontent.com/ConductionNL/waardepapieren-register/master/api/public/schema/openapi.yaml
      App\Entity\Authentication:
          authentication_1:
            name: conduction
            authenticateUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
            clientId: 85ef6bac-98b4-47fb-ae68-f248b91f6dde
            secret: 2_sIrT0BXCv..v_nP~UX_tF012RifW5a80
            scopes:
              - openid
              - profile

  location: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: acc-waardepapieren.hoorn.nl
  path: '/'
  pathType: ImplementationSpecific
  className: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
